# this is a Stencil for Kubernetes service.
apiVersion: v1
kind: Service
metadata:
  namespace: ${formation}
  name: ${concat(service, "-svc")}
  labels:
    app: ${stackname}
    tier: ${service}
spec:
  type: LoadBalancer   # This will create a GCE Load Balancer for you
  ports:
  - port: ${require("EXTERNAL_PORT")}
    targetPort: ${require("INTERNAL_PORT")}
  selector:
    app: ${stackname}
    tier: ${service}
