# this sets up the cluster with namepsace etc
# should be the first yaml to run
apiVersion: v1
kind: Namespace
metadata:
  name: ${formation}
---
apiVersion: v1
kind: Secret
metadata:
  namespace: ${formation}
  name: cloud66-registry-pull-secret
data:
  .dockerconfigjson: ${env("REGISTRY_AUTH")}  # Use a stack environment variable called REGISTRY_AUTH to store your docker registry credentials: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
type: kubernetes.io/dockerconfigjson
