# this is a sample stencil (redis)
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: ${formation}
  name: redis
<<<<<<< HEAD
=======
  annotations:
    cloud66.com/snapshot/uid: ${snapshot("uid")}
    cloud66.com/snapshot/gitref: ${snapshot("gitref")}
>>>>>>> 879b778082b841fc08db5a68e6119ceb202f3313
spec:
  template:
    metadata:
      labels: # be careful changing labels. It can break your deployment
        app: ${stackname}
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${formation}
  name: redis
<<<<<<< HEAD
=======
  annotations:
    cloud66.com/snapshot/uid: ${snapshot("uid")}
    cloud66.com/snapshot/gitref: ${snapshot("gitref")}
>>>>>>> 879b778082b841fc08db5a68e6119ceb202f3313
  labels:
    app: ${stackname}
    tier: redis
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: ${stackname}
    tier: redis

