# this is a Stencil for Kubernetes ConfigMaps. It adds any stack environment variable tagged with kube-secret to this file
kind: Secret
apiVersion: v1
metadata:
  namespace: ${formation}
  name: ${concat(stackname, "-envs")}
<<<<<<< HEAD
=======
  annotations:
    cloud66.com/snapshot/uid: ${snapshot("uid")}
    cloud66.com/snapshot/gitref: ${snapshot("gitref")}
>>>>>>> 879b778082b841fc08db5a68e6119ceb202f3313
  labels:
    app: ${stackname}
type: Opaque
data:
  ${envlist(2, "kube-secret")}
